sensor:
  - state_topic: "philips-air-purifier-coap/DEVICE_ID/attributes"
    name: "Power state (Airpurifier)"
    icon: "mdi:flash"
    value_template: "{{ value_json.state }}"
  - state_topic: "philips-air-purifier-coap/DEVICE_ID/attributes"
    name: "PM 2.5 (Airpurifier)"
    unit_of_measurement: "Index"
    icon: "mdi:chart-line"
    value_template: "{{ value_json.pm25 }}"
  - state_topic: "philips-air-purifier-coap/DEVICE_ID/attributes"
    name: "Mode (Airpurifier)"
    icon: "mdi:airplane"
    value_template: "{{ value_json.mode }}"
  - state_topic: "philips-air-purifier-coap/DEVICE_ID/attributes"
    name: "Humidity (Airpurifier)"
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    value_template: "{{ value_json.humidity }}"
  - state_topic: "philips-air-purifier-coap/DEVICE_ID/attributes"
    name: "Allergen index (Airpurifier)"
    unit_of_measurement: "Index"
    icon: "mdi:cloud-check-outline"
    value_template: "{{ value_json.allergen_index }}"
  - state_topic: "philips-air-purifier-coap/DEVICE_ID/attributes"
    name: "Temperature (Airpurifier)"
    unit_of_measurement: "Celsius"
    icon: "mdi:thermometer"
    value_template: "{{ value_json.temperature }}"
  - state_topic: "philips-air-purifier-coap/DEVICE_ID/attributes"
    name: "Target humidity (Airpurifier)"
    unit_of_measurement: "%"
    value_template: "{{ value_json.target_humidity }}"
    icon: "mdi:water-percent"
  - state_topic: "philips-air-purifier-coap/DEVICE_ID/attributes"
    name: "Child lock (Airpurifier)"
    value_template: >
        {% if value_json.child_lock == "True" %}
          On
        {% else %}
          Off
        {% endif %}
    icon: "mdi:human-child"
  - state_topic: "philips-air-purifier-coap/DEVICE_ID/attributes"
    name: "Function (Airpurifier)"
    value_template: "{{ value_json.function }}"
    icon: "mdi:function"
  - state_topic: "philips-air-purifier-coap/DEVICE_ID/attributes"
    name: "Display brightness (Airpurifier)"
    value_template: "{{ value_json.light_brightness }}"
    icon: "mdi:brightness-percent"
    unit_of_measurement: "%"
  - state_topic: "philips-air-purifier-coap/DEVICE_ID/attributes"
    name: "Water level (Airpurifier)"
    value_template: "{{ value_json.water_level }}"
    icon: "mdi:water"
    unit_of_measurement: "%"
  - state_topic: "philips-air-purifier-coap/DEVICE_ID/attributes"
    name: "Error (Airpurifier)"
    value_template: "{{ value_json.error }}"
